### ISSUE TITLE
Add `ghr` install to deploy CI task

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-http-client#110]

**Comment by carsonfarmer** [comment]
Could also just create a third `job` that does the github release. Originally added just to automate the release process, but since we don't have any assets to upload, maybe just using the github api via curl would be the easiest route?

**Comment by andrewxhill** [comment]
cool, up to you. just noticed it failing in the current ci

**Comment by carsonfarmer** [comment]
Closing this in favor of a simpler approach. No need to require ghr when there are node/npm tools available to use already.
