### ISSUE TITLE
Should we sync js-http-client major and minor versions with go-textile releases?

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-http-client#126]
I've seen some other projects do this. Would make checking compatibility between API versions easier? Obviously we can't/won't do this with patch versions, but let me know what you think? Good idea? Bad idea?

**Comment by balupton** [comment]
I imagine it makes sense only if the clients are generated together. As this is a manually made client, we probably want to publish releases when we change things accordingly, and respect semver which is very important to the javascript ecosystem.

We could probably have something where we communicate which go-textile version the client is compatible with, perhaps via `package.json:engines.go-textile`, or perhaps by us setting up a go-textile npm package, that installs the textile daemon if not already exists, and also does the version compatibility check.

That said, the most simple solution to all of this is we just note the compatible versions in the release notes of the clients.

**Comment by carsonfarmer** [comment]
Cool, I actually have an npm packing in the works that installs the textile daemon if it doesn't already exist, so that's certainly something we'll have available soonish. Having said that, I like your `package.json:engines.go-textile`, so I'll create a PR for that as well.

**Comment by balupton** [comment]
> Cool, I actually have an npm packing in the works that installs the textile daemon if it doesn't already exist, so that's certainly something we'll have available soonish.

Could totally use https://github.com/bevry/safeps for finding the binary through the PATH

**Comment by carsonfarmer** [comment]
Oh sweet, that is the second piece that I haven't started yet. The first module basically just fetches and installs the binary, but I haven't created a 'controller' for it yet to actually start the daemon. https://github.com/bevry/safeps could be what we build the controller with. The work is modeled after https://github.com/ipfs/js-ipfsd-ctl and related repos/projects. It'll come in really handy with the desktop work.

**Comment by carsonfarmer** [comment]
Closing this as we'll be using release notes to highlight version (in)compatibilities.
