### ISSUE TITLE
Unable to create wallet or restore wallet from http client since node isn't running until a wallet is initiated

### ISSUE THREAD

**Issue by polluterofminds** [textileio/js-http-client#133]
I might not be using the right terminology here, but the gist is this: 

I have an app where the user has their mnemonic somewhere (piece of paper, a password manager, SimpleID, wherever). Right now, for web apps, at least, the user has to be running the desktop tray app or the daemon. Unfortunately, I as a developer, don't have access to either of those systems until a wallet is already created or restored. 

It would be awesome to allow the daemon to run pre-initialization and feed it a recovery phrase to restore a wallet or feed it a command to create a new one from scratch. Those could then be new API calls in the js-http-client. 

I, clearly, have no idea how big of a lift it would be to allow the daemon (which I think is also running behind the scenes for the desktop tray app) to be started without a wallet initialized.

**Comment by carsonfarmer** [comment]
Thanks for the feature request @jehunter5811. Currently, its not _possible_ to have the daemon running without an initialized wallet... however, we could probably have a 'guest' wallet running (just an ephemeral wallet) and then reinitialize and restart with a new, user-provided wallet afterwards... Having said that... please take a look at: https://github.com/textileio/js-textile-go-daemon, which allows you to start/stop, and control a textile daemon from javascript.

**Comment by carsonfarmer** [comment]
Closing this as "won't fix" and in favour of using `js-textile-go-daemon`.
