### ISSUE TITLE
Thread model out of sync with go-textile (head_block)

### ISSUE THREAD

**Issue by connectdotz** [textileio/js-http-client#134]
looks like `go-textile` has moved to multiple head_blocks (textileio/go-textile#817). `Thread` now use [head_blocks](https://github.com/textileio/go-textile/blob/da179f756a2e14d43609ce7558ae35e12879343e/pb/protos/model.proto#L81) instead. But this package still has the old [head_block](https://github.com/textileio/js-http-client/blob/f46dde6165d43a25408aac3ae7e82ae783132c49/src/models/model_pb.ts#L51)...

**Comment by carsonfarmer** [comment]
Ah thanks for the catch here @connectdotz, will update shortly.
