### ISSUE TITLE
Not working with angular 8 (ReferenceError: global is not defined)

### ISSUE THREAD

**Issue by nlko** [textileio/js-http-client#138]
Hello,

I'm trying textile in an angular app.

If I try to call any API (like textile.config.get().then(...)) I receive an error in the chrome console:
```
polyfill.js:41 Uncaught ReferenceError: global is not defined
    at setup (polyfill.js:41)
    at Object../node_modules/@ef-carbon/fetch/dist/lib/polyfill.js (polyfill.js:54)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/@ef-carbon/fetch/install.js (install.js:6)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/@textile/js-http-client/dist/core/api.js (api.js:14)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/@textile/js-http-client/dist/modules/account.js (account.js:14)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/@textile/js-http-client/dist/index.js (index.js:9)
```
Some dependencies seems to use `global` while it's running from a browser. I tried to remove @ef-carbon/fetch but then the same error appears with the streams...

The strange thing is that it works with react!

Is there something I'm missing ? 

Could it be that the way the package is created is incompatible with angular ?

**Comment by carsonfarmer** [comment]
Hmm, interesting. It might be the way angular is bundling things? Do either of these workarounds address your problem:
* https://github.com/aws-amplify/amplify-js/issues/678#issuecomment-384260863
* https://github.com/aws-amplify/amplify-js/issues/678#issuecomment-389106098
* https://stackoverflow.com/questions/50371593/angular-6-uncaught-referenceerror-buffer-is-not-defined/50377270#50377270

**Comment by nlko** [comment]
Thanks for the suggestions, it helped me find a solution.

First, the index.html shall be modified this way:
```
<head>
  …
  <script>
    var global = global || window;
  </script>  
  …
</head>
```

Second, install Buffer : `yarn add buffer`

Third, I added the following code to the end of pollyfill.ts:
```
declare var global: {
    Buffer: any
};

declare var window: {
    process: any
};

import {Buffer} from 'buffer';

import * as process from 'process';

window.process = process;

global.Buffer = Buffer;

```
I was able to successfully execute `textile.config.get().then(x => console.dir(x));` this time. I haven't tried other API, I hope I didn't introduce any regression by doing so.

The same method worked also for ionic (angular).

There is still a mystery why it works perfectly with react.

**Comment by carsonfarmer** [comment]
I think it works with React because essentially, React does a bunch of these Polyfills automagically. I tested bundling with React, so I'm not surprised that it worked over other frameworks... But very pleased to hear this is now working for you!

**Comment by penguin-007** [comment]
> Thanks for the suggestions, it helped me find a solution.
> 
> First, the index.html shall be modified this way:
> 
> ```
> <head>
>   …
>   <script>
>     var global = global || window;
>   </script>  
>   …
> </head>
> ```
> 
> Second, install Buffer : `yarn add buffer`
> 
> Third, I added the following code to the end of pollyfill.ts:
> 
> ```
> declare var global: {
>     Buffer: any
> };
> 
> declare var window: {
>     process: any
> };
> 
> import {Buffer} from 'buffer';
> 
> import * as process from 'process';
> 
> window.process = process;
> 
> global.Buffer = Buffer;
> ```
> 
> I was able to successfully execute `textile.config.get().then(x => console.dir(x));` this time. I haven't tried other API, I hope I didn't introduce any regression by doing so.
> 
> The same method worked also for ionic (angular).
> 
> There is still a mystery why it works perfectly with react.

Thanks, it works for me with angular 8.
