### ISSUE TITLE
How come all other textile projects are TypeScript, but this is JavaScript?

### ISSUE THREAD

**Issue by balupton** [textileio/js-http-client#20]
One of the reasons I'm keen on Textile is their high code quality and usage of TypeScript. As such, I'd really like to see this project be coded in TypeScript too.

**Comment by carsonfarmer** [comment]
Just because we haven't got it to yet for this project. I'm creating a new ticket to track this, as you've prompted us to move on the switch more quickly :)

**Comment by carsonfarmer** [comment]
You can track the progress in #21.

**Comment by carsonfarmer** [comment]
Fixed with #21 now closed
