### ISSUE TITLE
Switch to TypeScript

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-http-client#21]
All our other JS projects are written in TypeScript, this one should be as well. Making the switch now will be much easier while we have less technical dept.

**Comment by andrewxhill** [comment]
fixed here https://github.com/textileio/js-http-client/pull/28

**Comment by carsonfarmer** [comment]
Due to some issues with working with the pb types exported for mobile, I have created an alternative set of types, directly exported from go, using a fork of `protoc-gen-jsonpb-ts` (https://github.com/carsonfarmer/protoc-gen-jsonpb-ts). For now, I'm including these types with `js-http-client`, but we should probably have this in their own package at some point to make publishing easier.
In any case, this means we have JSON friendly types for this lib. Leaving this Epic open until all changes are merged and in master.

**Comment by carsonfarmer** [comment]
Fixed with #28 + #38 + #40
