### ISSUE TITLE
Initial TypeScript switch

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-http-client#22]
For this initial work, simply use `:any` as the return value on most functions and methods, just to get things going.

**Comment by sanderpick** [comment]
Another approach would be just to each file _correctly_ one by one... just blasting through with _any_ doesn't accomplish anything.

**Comment by andrewxhill** [comment]
this was my idea and the idea wasn't to `:any` all types, just those we are missing from `pb` until/unless there is an easy way to get that module published for this client. that would allow us to not be blocked by those types and still move forward with typescript sooner than later

**Comment by carsonfarmer** [comment]
Yeh, I guess _most_ wasn't very clear. Just the ones that we're missing/need to be exported from pb.

**Comment by sanderpick** [comment]
Okay, nice. Makes sense. You could just import `go-mobile` for now... ?

**Comment by carsonfarmer** [comment]
We could, just comes with a lot of baggage at the moment, when all we really need are the types. It is possible to just pull the types from a module?

**Comment by sanderpick** [comment]
The actual package is actually just the types... you're just gonna get the frameworks from the post install script. Just a couple of files you could delete for now. We're going to move the framework distribution off of npm anyway. So, I'd imagine go-mobile will just become _only_ the types anyway. The types are generated in the go proj... it should be the source.

**Comment by carsonfarmer** [comment]
Ok cool, that's great.

**Comment by andrewxhill** [comment]
fixed in https://github.com/textileio/js-http-client/pull/28

**Comment by andrewxhill** [comment]
closing for https://github.com/textileio/js-http-client/issues/21
