### ISSUE TITLE
Proper output types from pb module

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-http-client#23]
This will likely be a tedious task, but will help us big time in the long run. We only really need to interfaces exported from `@textileio/go-mobile`, so not quite sure the best way to tackle this initially, but should be easy to figure out.

**Comment by andrewxhill** [comment]
fixed in https://github.com/textileio/js-http-client/pull/28
for now i just import the whole shebang, easy follow on if you know the trick
