### ISSUE TITLE
Be sure to use same hierarchical structure of modules to RN sdk

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-http-client#3]
Can follow along here: https://github.com/textileio/react-native-sdk/tree/sander/go-mobile-rc47/lib/Textile/API for now

**Comment by andrewxhill** [comment]
That hierarchy shoudl be in master of rn sdk now. This should probably be done before any public post including the api methods specifically.

**Comment by carsonfarmer** [comment]
This is on track now in master and typescript branches
