### ISSUE TITLE
Improve type selection for the http methods

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-http-client#32]
In `src/core/api.js` there was the use of args, opts, headers, data and I chose pretty basic types for those for now. they probably are all pass through types from underlying requesting libraries. I just didn't try to unravel it in the first Typescript PR, should be a quick one.

**Comment by carsonfarmer** [comment]
For the args, opts, headers, and data, I think what @andrewxhill did here is correct/good. They are pretty generic. However, with #38 we now also have return types for the API, which should be enough for now.
