### ISSUE TITLE
Remove /dist from git history

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-http-client#33]

**Comment by carsonfarmer** [comment]
Do you want to do a whole history purge here, a la (https://stackoverflow.com/a/17824718/1256988), or just do a git rm -rf dist/ and leave the old stuff in history. Its not a lot of files, so probs not the end of the world to leave them? But happy to do the whole purge in my current work.

**Comment by andrewxhill** [comment]
i wouldn't worry about history

**Comment by carsonfarmer** [comment]
Done with #34
