### ISSUE TITLE
Drop as many custom rules in tslint

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-http-client#36]
A bunch of custom rules are still in play,

https://github.com/textileio/js-http-client/blob/master/tslint.json#L38

we could try to drop and/or move to the common rules as many as we can. there may be some necessary custom ones but probably not that many.

**Comment by carsonfarmer** [comment]
We should be able to drop:

- [ ] "semicolon": [true, "never"]
- [ ] "no-shadowed-variable": false
- [ ] "no-null-keyword": true
- [ ] "no-var-requires": false
- [ ] "no-string-literal": false
- [ ] "no-this-assignment": false
- [ ] "no-submodule-imports": false
- [ ] "variable-name": false
- [ ] "no-console": [true, "log"]
- [ ] "no-namespace": [false]
- [ ] "no-implicit-dependencies": [true, "dev"]
- [ ] "max-classes-per-file": false
- [ ] "object-literal-sort-keys": false
- [ ] "ordered-imports": false

We can probably also drop all `jsRules` now that we don't have any js files to lint.
