### ISSUE TITLE
Browser bundler distribution 

### ISSUE THREAD

**Issue by sanderpick** [textileio/js-http-client#58]
Was working though a user-reported bug and found that it took a good amount of effort to test in the browser, (webpack-ed, exposed global var, etc.).

- Add a bundle step to the package.json?
- Add it to a CDN?

**Comment by carsonfarmer** [comment]
Good idea sander. So far we (Textile) have been using webpack to test in browser. But haven’t included that work here yet to avoid the extra deps. But if we make them dev deps, not really a big deal. Will add script for this.
