### ISSUE TITLE
Error responses are parsed as JSON

### ISSUE THREAD

**Issue by sanderpick** [textileio/js-http-client#61]
In the current state of the HTTP API, errors are returned as strings. Anything above code 400 should be parsed as a string.

<img width="1238" alt="Screen Shot 2019-04-26 at 7 09 33 AM" src="https://user-images.githubusercontent.com/361000/56813666-4b9f7a00-67f2-11e9-8dae-20b8eea22b9f.png">

**Comment by carsonfarmer** [comment]
Ah yes. This is a ‘feature’ of our move to fetch api. Only network errors automatically throw. Missed this fact in the conversion. Should be an easy find and replace fix.
