### ISSUE TITLE
fetch requests all (mostly) fail after the tray has been running for a while

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-http-client#63]
`textile.account.address` succeeds

`textile.profile.name` fails as do others like `addFile` etc. 

strange, but I'm guessing it has something to do with the fetch lib. 

once this happens, all you see are JSON parse errors (https://github.com/textileio/js-http-client/issues/61) coming from the `return response.json()` attempts. but the content of those responses are, 

### when successful

```Response { type: "cors", url: "http://localhost:40602/api/v0/profile", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers, body: ReadableStream, bodyUsed: false }```

### when failing after idle

```Response { type: "cors", url: "http://localhost:40602/api/v0/profile", redirected: false, status: 400, ok: false, statusText: "Bad Request", headers: Headers, body: ReadableStream, bodyUsed: false }```

**Comment by carsonfarmer** [comment]
Hmmm. This might be an issue with readable streams being left ‘open’?
