### ISSUE TITLE
files.add should take arbitrary valid JSON/JS objects

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-http-client#72]
This can be stringified in the background, but the user should be able to add these objects directly. This would make for a nicer experience in the Textile tour as well.

**Comment by andrewxhill** [comment]
been finding this helpful,

https://github.com/textileio/docs/pull/44/files#diff-628a92345466981556dd5bacb9cb997f

going through each of the tour examples and looking for parity

**Comment by carsonfarmer** [comment]
Yup suuuuper helpful. That's where I got the idea for this issue from :)

**Comment by carsonfarmer** [comment]
Fixed with #92
