### ISSUE TITLE
Have http-client check for running REST API version

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-http-client#79]
This would help us ensure we can query certain endpoints or not. For a first pass, perhaps just console.warning if the versions don't match?

**Comment by carsonfarmer** [comment]
@andrewxhill for this, what about just an additional method on the Textile class? Something like:

`Textile.checkVersion()` which returns boolean whether node version matches?

**Comment by andrewxhill** [comment]
wont fix, replaced by new apis.
